### ISSUE TITLE
CSS Grid

### ISSUE THREAD

**Issue by luchoPenafiel** [famallamaci/Curso-CSS#3]
Hola Fran! Te dejo una inconsistencia que encontré en la sección de CSS Grid:

Al `contenedor` le estas diciendo que sea un grid de 2 columnas, la primera de 200px y la otra de 100px.
https://github.com/famallamaci/Curso-CSS/blob/28627958166a5c362d5e1e191af4e039c8fcfa77/css-grid/style.css#L9
Esto no sería correcto porque luego, en la segunda columna tienes un subgrid de 3 columnas de 200px cada una.
https://github.com/famallamaci/Curso-CSS/blob/28627958166a5c362d5e1e191af4e039c8fcfa77/css-grid/style.css#L21
Este subgrid es más grande que su columna. Me explico? Te dejo una imagen de referencia donde se ven resaltada la columna 1 y 2 y vas a ver claramente que la 2 mide la mitad de la primera columna del subgrid, es decir, 100px.    
![Captura de Pantalla 2019-10-30 a la(s) 07 32 30](https://user-images.githubusercontent.com/25674406/67850625-85c23f00-fae7-11e9-9741-32a9e8af5691.png)

Qué solución le daría yo? Simple, a la segunda columna, en lugar de asignarle un valor de 100px, le pondría uno de 600px.

**Comment by famallamaci** [comment]
Corregido
